In [1]:
# -*- coding: utf-8 -*- 

import tensorflow as tf

In [2]:
import numpy as np

In [3]:
cnt = 0
model_path = "./variables"

In [4]:
tf.set_random_seed(777)

In [5]:
xy = np.loadtxt('trainingdata.csv', delimiter=',', dtype=np.float32)

In [6]:
x_data = xy[:, 0:-2]
y_data = xy[:, -2:]

print(x_data)
print(y_data)

[[-63. -92. -72. -72.]
 [-63. -90. -72. -72.]
 [-64. -90. -72. -74.]
 ...
 [-86. -95. -76. -59.]
 [-87. -95. -76. -59.]
 [-89. -94. -77. -59.]]
[[ 1. 16.]
 [ 1. 16.]
 [ 1. 16.]
 ...
 [10.  4.]
 [10.  4.]
 [10.  4.]]


In [7]:
X = tf.placeholder(tf.float32, name='X')
Y = tf.placeholder(tf.float32, name='Y')

keep_prob = 1

In [8]:
W1 = tf.get_variable("W1", shape=[4, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W2 = tf.get_variable("W2", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W3 = tf.get_variable("W3", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W4 = tf.get_variable("W4", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W5 = tf.get_variable("W5", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W6 = tf.get_variable("W6", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W7 = tf.get_variable("W7", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W8 = tf.get_variable("W8", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W9 = tf.get_variable("W9", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W10 = tf.get_variable("W10", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W11 = tf.get_variable("W11", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W12 = tf.get_variable("W12", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W13 = tf.get_variable("W13", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W14 = tf.get_variable("W14", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W15 = tf.get_variable("W15", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W16 = tf.get_variable("W16", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W17 = tf.get_variable("W17", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
W18 = tf.get_variable("W18", shape=[128, 128], initializer=tf.contrib.layers.variance_scaling_initializer())
out = tf.get_variable("out", shape=[128, 2], initializer=tf.contrib.layers.variance_scaling_initializer())

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



In [9]:
L1 = tf.nn.relu(tf.matmul(X, W1))
L1 = tf.nn.dropout(L1, keep_prob)

L2 = tf.nn.relu(tf.matmul(L1, W2))
L2 = tf.nn.dropout(L2, keep_prob)

L3 = tf.nn.relu(tf.matmul(L2, W3))
L3 = tf.nn.dropout(L3, keep_prob)

L4 = tf.nn.relu(tf.matmul(L3, W4))
L4 = tf.nn.dropout(L4, keep_prob)

L5 = tf.nn.relu(tf.matmul(L4, W5))
L5 = tf.nn.dropout(L5, keep_prob)

L6 = tf.nn.relu(tf.matmul(L5, W6))
L6 = tf.nn.dropout(L6, keep_prob)

L7 = tf.nn.relu(tf.matmul(L6, W7))
L7 = tf.nn.dropout(L7, keep_prob)

L8 = tf.nn.relu(tf.matmul(L7, W8))
L8 = tf.nn.dropout(L8, keep_prob)

L9 = tf.nn.relu(tf.matmul(L8, W9))
L9 = tf.nn.dropout(L9, keep_prob)

L10 = tf.nn.relu(tf.matmul(L9, W10))
L10 = tf.nn.dropout(L10, keep_prob)

L11 = tf.nn.relu(tf.matmul(L10, W11))
L11 = tf.nn.dropout(L11, keep_prob)

L12 = tf.nn.relu(tf.matmul(L11, W12))
L12 = tf.nn.dropout(L12, keep_prob)

L13 = tf.nn.relu(tf.matmul(L12, W13))
L13 = tf.nn.dropout(L13, keep_prob)

L14 = tf.nn.relu(tf.matmul(L13, W14))
L14 = tf.nn.dropout(L14, keep_prob)

L15 = tf.nn.relu(tf.matmul(L14, W15))
L15 = tf.nn.dropout(L15, keep_prob)

L16 = tf.nn.relu(tf.matmul(L15, W16))
L16 = tf.nn.dropout(L16, keep_prob)

L17 = tf.nn.relu(tf.matmul(L16, W17))
L17 = tf.nn.dropout(L17, keep_prob)

L18 = tf.nn.relu(tf.matmul(L17, W18))
L18 = tf.nn.dropout(L18, keep_prob)

hypothesis = tf.matmul(L18, out)

h = tf.identity(hypothesis, name='h')

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [10]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.000001)
train_op = optimizer.minimize(cost)

In [11]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

saver = tf.train.Saver()
saver.restore(sess, model_path)

INFO:tensorflow:Restoring parameters from ./variables


In [13]:
for step in range(100000000):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})
    
    if (step + 1) % 100000 == 0:
        cnt = cnt + 1
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
        builder = tf.saved_model.builder.SavedModelBuilder("/ZStep"+str(cnt)+"Projectfinal/fromPython")
        builder.add_meta_graph_and_variables(sess,[tf.saved_model.tag_constants.SERVING])
        builder.save()
        saver.save(sess, model_path)

99800000 0.5950028
INFO:tensorflow:No assets to save.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: /ZStep10004Projectfinal/fromPython\saved_model.pb
